apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stage
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stage
  template:
    metadata:
      labels:
        app: nginx-stage
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
